[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/tv"
  to = "https://twitch.tv/donaldpakkies"
  status = 200 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Server = 'Ubuntu'
    X-Powered-By = 'Ubuntu'
